#!/bin/sh
git config --global user.name "Tiensbakung"
git config --global user.email "Tiensbakung@gmail.com"
git config --global color.ui auto
git config --global core.editor "vim"
git config --global alias.graph 'log --graph --oneline --decorate'
git config --global core.excludesfile '~/.gitignore'
